import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./tcc/auth";
import checkinRouter from "./tcc/checkin";
import journalRouter from "./tcc/journal";
import briefRouter from "./tcc/brief";
import emailsRouter from "./tcc/emails";
import contactsRouter from "./tcc/contacts";
import callsRouter from "./tcc/calls";
import ideasRouter from "./tcc/ideas";
import claudeRouter from "./tcc/claude";
import demosRouter from "./tcc/demos";
import tasksRouter from "./tcc/tasks";
import eodRouter from "./tcc/eod";
import systemInstructionsRouter from "./tcc/system-instructions";
import phoneLogRouter from "./tcc/phone-log";
import sendSmsRouter from "./tcc/send-sms";
import timeRoutingRouter from "./tcc/time-routing";
import meetingHistoryRouter from "./tcc/meeting-history";
import emailSendRouter from "./tcc/email-send";
import contactsAutocompleteRouter from "./tcc/contacts-autocomplete";
import emailPollRouter from "./tcc/email-poll";
import communicationLogRouter from "./tcc/communication-log";
import chatThreadsRouter from "./tcc/chat-threads";
import salesMorningRouter from "./tcc/sales-morning";
import contactsScoreRouter from "./tcc/contacts-score";
import contactsResearchRouter from "./tcc/contacts-research";
import contactsBriefRouter from "./tcc/contacts-brief";
import sheetsSyncRouter from "./tcc/sheets-sync";
import sheetScanRouter from "./tcc/sheet-scan";
import linearRouter from "./tcc/linear";
import scheduleRouter from "./tcc/schedule";
import driveRouter from "./tcc/drive";
import notesScratchRouter from "./tcc/notes-scratch";
import demoFeedbackRouter from "./tcc/demo-feedback";
import businessRouter from "./tcc/business";
import planRouter from "./tcc/plan";
import cronRouter from "./tcc/cron";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(checkinRouter);
router.use(journalRouter);
router.use(briefRouter);
router.use(emailsRouter);
router.use(contactsAutocompleteRouter);
router.use(contactsRouter);
router.use(callsRouter);
router.use(ideasRouter);
router.use(claudeRouter);
router.use(demosRouter);
router.use(tasksRouter);
router.use(eodRouter);
router.use(systemInstructionsRouter);
router.use(phoneLogRouter);
router.use(sendSmsRouter);
router.use(timeRoutingRouter);
router.use(meetingHistoryRouter);
router.use(emailSendRouter);
router.use(emailPollRouter);
router.use(communicationLogRouter);
router.use(chatThreadsRouter);
router.use(salesMorningRouter);
router.use(contactsScoreRouter);
router.use(contactsResearchRouter);
router.use(contactsBriefRouter);
router.use(sheetsSyncRouter);
router.use(sheetScanRouter);
router.use(linearRouter);
router.use(scheduleRouter);
router.use(driveRouter);
router.use(notesScratchRouter);
router.use(demoFeedbackRouter);
router.use(businessRouter);
router.use(planRouter);
router.use(cronRouter);

// ─── Canonical aliases ────────────────────────────────────────────────────────
router.post("/email-action", (req: import("express").Request, res: import("express").Response, next: import("express").NextFunction) => {
  req.url = "/emails/action";
  emailsRouter(req, res, next);
});
router.post("/call-log", (req: import("express").Request, res: import("express").Response, next: import("express").NextFunction) => {
  req.url = "/calls";
  callsRouter(req, res, next);
});
router.post("/idea", (req: import("express").Request, res: import("express").Response, next: import("express").NextFunction) => {
  req.url = "/ideas";
  ideasRouter(req, res, next);
});

export default router;
